# Generated by Django 4.2.1 on 2023-06-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
