# Generated by Django 4.2.2 on 2023-06-25 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_bookmark_bookmarked'),
        ('main', '0031_post_comment_count_post_like_count'),
    ]

    operations = [
    ]
